# Train node configuration

credential : "********" # Auth password

hp_config: MNIST-LeNet1
hp_config_dir: ./hp_conf/

eval_func: optimize_mnist_lenet1
port: 6100

resource_type: cpu
resource_id: 1

debug_mode: true