# Train node configuration

credential : "********" # Auth password. Set to be same between hpo_runner and train_node

hp_config: kin8nm-MLP   # The same hyperparameter configuration should be used between hpo_runner and train_node 
hp_config_dir: ./hp_conf/

eval_func: optimize_kin8nm_mlp # See the code in train_node
port: 6100

resource_type: cpu  # running on CPU
resource_id: 0

debug_mode: false # Set true to show debug messages