# Train node configuration

credential : "********" # Auth password

hp_config: protein-MLP
hp_config_dir: ./hp_conf/

eval_func: tune_protein_mlp
port: 6101

resource_type: cpu
resource_id: 1

debug_mode: true