# Train node configuration

credential : "********" # Auth password. Set to be same between hpo_runner and train_node

hp_config: CIFAR100-efficientnet
hp_config_dir: ./hp_conf/

train_node:
    eval_func: tune_efficientnet_cifar100
    port: 6101 # Set the port number that is not used
    resource_type: gpu
    resource_id: 1

debug_mode: false # Set true to show debug messages