# Train node configuration

credential : "********" # Auth password

hp_config: protein-MLP
hp_config_dir: ./hp_conf/

train_node:
    eval_func: tune_protein_mlp # See the code in train_node
    port: 6101
    resource_type: cpu
    resource_id: 1
    log: train_protein.log


debug_mode: true