# Train node configuration

credential : "********" # Auth password

hp_config: kin8nm-MLP
hp_config_dir: ./hp_conf/

eval_func: optimize_kin8nm_mlp
port: 6100

resource_type: cpu
resource_id: 0

debug_mode: true